const ADD_INFO_LOGIN = 'ADD_INFO_LOGIN';
const ADD_INFO_PROFILE = 'ADD_INFO_PROFILE';
const ALERT_SUCCESS = 'ALERT_SUCCESS';
const ALERT_FAILURE = 'ALERT_FAILURE';
const PENDING_API = 'PENDING_API';

export {
	ADD_INFO_LOGIN,
	ADD_INFO_PROFILE,
	ALERT_SUCCESS,
	ALERT_FAILURE,
	PENDING_API,
};
